# Generated by Django 5.0.6 on 2024-08-23 08:03

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SentimentScore",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("text", models.TextField(verbose_name="Text")),
                (
                    "score",
                    models.DecimalField(
                        decimal_places=3, max_digits=4, verbose_name="Sentiment Score"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
            ],
        ),
    ]
